package net.lepidodendron.util;

public class SpawnerConfigsPrecambrian {

    public static String[] dimHadeanMobsPF = new String[0];
    public static String[] dimArcheanMobsPF = new String[0];
    public static String[] dimPaleoproterozoicMobsPF = new String[0];
    public static String[] dimMesoproterozoicMobsPF = new String[0];
    public static String[] dimNeoproterozoicMobsPF = new String[0];
    public static String[] dimCryogenianMobsPF = new String[]{"lepidodendron:prehistoric_flora_cyclomedusa:6:6:7","lepidodendron:prehistoric_flora_ediacaria:3:6:4","lepidodendron:prehistoric_flora_nimbia:6:6:7"};
    public static String[] dimTonianMobsPF = new String[]{"lepidodendron:prehistoric_flora_cyclomedusa:6:6:7","lepidodendron:prehistoric_flora_ediacaria:3:6:4"};
    public static String[] dimEdiacaranMobsPF = new String[]{"lepidodendron:prehistoric_flora_nimbia:12:7:7","lepidodendron:prehistoric_flora_cyclomedusa:12:7:7", "lepidodendron:prehistoric_flora_attenborites:12:7:4","lepidodendron:prehistoric_flora_dickinsonia:2:10:4","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:12:4","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_parvancorina:3:13:4","lepidodendron:prehistoric_flora_spriggina:3:12:4","lepidodendron:prehistoric_flora_yilingia:2:14:4","lepidodendron:prehistoric_flora_yorgia:3:13:4"};
    public static String[] dimEdiacaranSparseMobsPF = new String[]{"lepidodendron:prehistoric_flora_nimbia:12:7:7","lepidodendron:prehistoric_flora_cyclomedusa:12:7:7", "lepidodendron:prehistoric_flora_attenborites:12:7:4","lepidodendron:prehistoric_flora_dickinsonia:2:10:4","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:12:4","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_parvancorina:3:13:4","lepidodendron:prehistoric_flora_spriggina:3:12:4","lepidodendron:prehistoric_flora_yilingia:2:14:4","lepidodendron:prehistoric_flora_yorgia:3:13:4"};
    public static String[] dimEdiacaranTrenchMobsPF = new String[]{"lepidodendron:prehistoric_flora_nimbia:12:7:7","lepidodendron:prehistoric_flora_cyclomedusa:12:7:7", "lepidodendron:prehistoric_flora_attenborites:12:7:4","lepidodendron:prehistoric_flora_dickinsonia:2:10:4","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:12:4","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_parvancorina:3:13:4","lepidodendron:prehistoric_flora_spriggina:3:12:4","lepidodendron:prehistoric_flora_yilingia:2:14:4","lepidodendron:prehistoric_flora_yorgia:3:13:4"};
    public static String[] dimEdiacaranHillsMobsPF = new String[]{"lepidodendron:prehistoric_flora_nimbia:12:7:7","lepidodendron:prehistoric_flora_cyclomedusa:12:7:7", "lepidodendron:prehistoric_flora_attenborites:12:7:4","lepidodendron:prehistoric_flora_dickinsonia:2:10:4","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:12:4","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_parvancorina:3:13:4","lepidodendron:prehistoric_flora_spriggina:3:12:4","lepidodendron:prehistoric_flora_yilingia:2:14:4","lepidodendron:prehistoric_flora_yorgia:3:13:4"};
    public static String[] dimEdiacaranStromatoliteMobsPF = new String[]{"lepidodendron:prehistoric_flora_nimbia:12:7:7","lepidodendron:prehistoric_flora_cyclomedusa:12:7:7", "lepidodendron:prehistoric_flora_attenborites:12:7:4","lepidodendron:prehistoric_flora_dickinsonia:2:10:4","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:12:4","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_parvancorina:3:13:4","lepidodendron:prehistoric_flora_spriggina:3:12:4","lepidodendron:prehistoric_flora_yilingia:2:14:4","lepidodendron:prehistoric_flora_yorgia:3:13:4"};
    public static String[] dimEdiacaranFrondoseMobsPF = new String[]{"lepidodendron:prehistoric_flora_nimbia:12:7:7","lepidodendron:prehistoric_flora_cyclomedusa:12:7:7", "lepidodendron:prehistoric_flora_attenborites:12:7:4","lepidodendron:prehistoric_flora_dickinsonia:2:10:4","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:12:4","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_parvancorina:3:13:4","lepidodendron:prehistoric_flora_spriggina:3:12:4","lepidodendron:prehistoric_flora_yilingia:2:14:4","lepidodendron:prehistoric_flora_yorgia:3:13:4"};
    public static String[] dimEdiacaranShallowMobsPF = new String[]{"lepidodendron:prehistoric_flora_nimbia:12:7:7","lepidodendron:prehistoric_flora_cyclomedusa:12:7:7", "lepidodendron:prehistoric_flora_attenborites:12:7:4","lepidodendron:prehistoric_flora_dickinsonia:2:10:4","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:12:4","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_parvancorina:3:13:4","lepidodendron:prehistoric_flora_spriggina:3:12:4","lepidodendron:prehistoric_flora_yilingia:2:14:4","lepidodendron:prehistoric_flora_yorgia:3:13:4"};
    public static String[] dimEdiacaranReefMobsPF = new String[]{"lepidodendron:prehistoric_flora_nimbia:12:7:7","lepidodendron:prehistoric_flora_cyclomedusa:12:7:7", "lepidodendron:prehistoric_flora_attenborites:12:7:4","lepidodendron:prehistoric_flora_dickinsonia:2:10:4","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:12:4","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_parvancorina:3:13:4","lepidodendron:prehistoric_flora_spriggina:3:12:4","lepidodendron:prehistoric_flora_yilingia:2:14:4","lepidodendron:prehistoric_flora_yorgia:3:13:4"};

    //------------ Fossils and Archeology mobs:
    public static String[] dimEdiacaranMobsFA = new String[0];

    //------------ Reborn mobs:
    public static String[] dimEdiacaranMobsReborn = new String[0];

}
