package net.lepidodendron.util;

public class SpawnerConfigsPrecambrian {

    public static String[] dimHadeanMobsPF = new String[0];
    public static String[] dimArcheanMobsPF = new String[0];
    public static String[] dimPaleoproterozoicMobsPF = new String[0];
    public static String[] dimMesoproterozoicMobsPF = new String[0];
    public static String[] dimNeoproterozoicMobsPF = new String[0];
    public static String[] dimCryogenianMobsPF = new String[]{"lepidodendron:prehistoric_flora_rugoconites:2:1:7", "lepidodendron:prehistoric_flora_rugoconites:2:1:3","lepidodendron:prehistoric_flora_cyclomedusa:6:6:7","lepidodendron:prehistoric_flora_cyclomedusa:6:6:3","lepidodendron:prehistoric_flora_ediacaria:3:6:4","lepidodendron:prehistoric_flora_nimbia:6:6:7","lepidodendron:prehistoric_flora_nimbia:6:6:3"};
    public static String[] dimTonianMobsPF = new String[]{"lepidodendron:prehistoric_flora_cyclomedusa:6:6:7","lepidodendron:prehistoric_flora_cyclomedusa:6:6:3","lepidodendron:prehistoric_flora_ediacaria:3:6:4"};
    public static String[] dimEdiacaranSparseSeaMobsPF = new String[0];
    public static String[] dimEdiacaranTrenchMobsPF = new String[]{"lepidodendron:prehistoric_flora_cyclomedusa:6:6:7","lepidodendron:prehistoric_flora_cyclomedusa:6:6:3"};
    public static String[] dimEdiacaranExtremeHillsMobsPF = new String[]{"lepidodendron:prehistoric_flora_ovatoscutum:3:23:7","lepidodendron:prehistoric_flora_ovatoscutum:3:23:3","lepidodendron:prehistoric_flora_cyanorus:3:23:7","lepidodendron:prehistoric_flora_cyanorus:3:23:3","lepidodendron:prehistoric_flora_cephalonega:3:23:7","lepidodendron:prehistoric_flora_cephalonega:3:23:3","lepidodendron:prehistoric_flora_andiva:3:23:7","lepidodendron:prehistoric_flora_andiva:3:23:3","lepidodendron:prehistoric_flora_ichnusa:6:10:4","lepidodendron:prehistoric_flora_eoporpita:6:10:4","lepidodendron:prehistoric_flora_temnoxa:3:23:7", "lepidodendron:prehistoric_flora_temnoxa:3:23:3","lepidodendron:prehistoric_flora_tribrachidiummob:3:20:7","lepidodendron:prehistoric_flora_tribrachidiummob:3:20:3","lepidodendron:prehistoric_flora_anfesta:3:20:7", "lepidodendron:prehistoric_flora_anfesta:3:20:3","lepidodendron:prehistoric_flora_cyclomedusa:6:6:7","lepidodendron:prehistoric_flora_cyclomedusa:6:6:3","lepidodendron:prehistoric_flora_attenborites:12:20:4","lepidodendron:prehistoric_flora_dickinsonia:2:20:7","lepidodendron:prehistoric_flora_dickinsonia:2:20:3","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:20:7", "lepidodendron:prehistoric_flora_kimberella:3:20:3","lepidodendron:prehistoric_flora_parvancorina:3:20:7","lepidodendron:prehistoric_flora_parvancorina:3:20:3","lepidodendron:prehistoric_flora_yorgia:3:20:7", "lepidodendron:prehistoric_flora_yorgia:3:20:3"};
    public static String[] dimEdiacaranStromatolitePavementMobsPF = new String[]{"lepidodendron:prehistoric_flora_karakhtia:3:23:7","lepidodendron:prehistoric_flora_karakhtia:3:23:3","lepidodendron:prehistoric_flora_keretsa:3:23:7","lepidodendron:prehistoric_flora_keretsa:3:23:3","lepidodendron:prehistoric_flora_quaestio:3:23:7","lepidodendron:prehistoric_flora_quaestio:3:23:3","lepidodendron:prehistoric_flora_uncus:3:23:7","lepidodendron:prehistoric_flora_uncus:3:23:3","lepidodendron:prehistoric_flora_ikaria:3:23:7","lepidodendron:prehistoric_flora_ikaria:3:23:3","lepidodendron:prehistoric_flora_ovatoscutum:3:23:7","lepidodendron:prehistoric_flora_ovatoscutum:3:23:3","lepidodendron:prehistoric_flora_eoporpita:6:10:4","lepidodendron:prehistoric_flora_hallidaya:3:60:7","lepidodendron:prehistoric_flora_hallidaya:3:60:3","lepidodendron:prehistoric_flora_nimbia:6:60:7","lepidodendron:prehistoric_flora_nimbia:6:60:3","lepidodendron:prehistoric_flora_cyclomedusa:6:60:7","lepidodendron:prehistoric_flora_cyclomedusa:6:60:3","lepidodendron:prehistoric_flora_ediacaria:6:18:4"};
    public static String[] dimEdiacaranFrondoseMobsPF = new String[]{"lepidodendron:prehistoric_flora_andiva:3:23:7","lepidodendron:prehistoric_flora_andiva:3:23:3","lepidodendron:prehistoric_flora_tribrachidiummob:3:12:7","lepidodendron:prehistoric_flora_tribrachidiummob:3:12:3","lepidodendron:prehistoric_flora_rugoconites:3:12:7", "lepidodendron:prehistoric_flora_rugoconites:3:12:3","lepidodendron:prehistoric_flora_cyclomedusa:6:6:7","lepidodendron:prehistoric_flora_cyclomedusa:6:6:3","lepidodendron:prehistoric_flora_attenborites:12:15:4","lepidodendron:prehistoric_flora_dickinsonia:2:10:7","lepidodendron:prehistoric_flora_dickinsonia:2:10:3","lepidodendron:prehistoric_flora_ediacaria:6:10:4","lepidodendron:prehistoric_flora_kimberella:3:12:7", "lepidodendron:prehistoric_flora_kimberella:3:12:3","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_parvancorina:3:13:7","lepidodendron:prehistoric_flora_parvancorina:3:13:3","lepidodendron:prehistoric_flora_spriggina:3:12:4","lepidodendron:prehistoric_flora_yorgia:3:13:7", "lepidodendron:prehistoric_flora_yorgia:3:13:3"};
    public static String[] dimEdiacaranShallowSeaMobsPF = new String[]{"lepidodendron:prehistoric_flora_eoporpita:6:10:4","lepidodendron:prehistoric_flora_tribrachidiummob:3:12:7","lepidodendron:prehistoric_flora_tribrachidiummob:3:12:3","lepidodendron:prehistoric_flora_rugoconites:3:12:7", "lepidodendron:prehistoric_flora_rugoconites:3:12:3","lepidodendron:prehistoric_flora_cyclomedusa:6:6:7","lepidodendron:prehistoric_flora_cyclomedusa:6:6:3","lepidodendron:prehistoric_flora_dickinsonia:2:10:7","lepidodendron:prehistoric_flora_dickinsonia:2:10:3","lepidodendron:prehistoric_flora_eoandromeda:10:10:4","lepidodendron:prehistoric_flora_yilingia:7:14:7","lepidodendron:prehistoric_flora_yilingia:7:14:3"};
    public static String[] dimEdiacaranShallowReefMobsPF = new String[]{"lepidodendron:prehistoric_flora_lobodiscus:3:22:7","lepidodendron:prehistoric_flora_lobodiscus:3:22:3","lepidodendron:prehistoric_flora_nimbia:6:26:7","lepidodendron:prehistoric_flora_nimbia:6:26:3","lepidodendron:prehistoric_flora_kimberella:3:26:7", "lepidodendron:prehistoric_flora_kimberella:3:26:3","lepidodendron:prehistoric_flora_yilingia:3:24:7","lepidodendron:prehistoric_flora_yilingia:3:24:3","lepidodendron:prehistoric_flora_alienum:2:15:4","lepidodendron:prehistoric_flora_alienum:2:15:3"};

    //------------ Fossils and Archeology mobs:
    public static String[] dimEdiacaranMobsFA = new String[0];

    //------------ Reborn mobs:
    public static String[] dimEdiacaranMobsReborn = new String[0];

}
