package net.lepidodendron.entity.render.tile;

import net.lepidodendron.LepidodendronMod;
import net.lepidodendron.block.BlockDisplayWallMount;
import net.lepidodendron.entity.model.entity.*;
import net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer;
import net.minecraft.util.ResourceLocation;

public class RenderDisplays extends TileEntitySpecialRenderer<BlockDisplayWallMount.TileEntityDisplayWallMount> {

    public static final ResourceLocation TEXTURE_APHNELEPIS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/aphnelepis.png");
    public static final ModelAphnelepis modelAphnelepis = new ModelAphnelepis();
    public static final ResourceLocation TEXTURE_AETHEOLEPIS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/aetheolepis.png");
    public static final ModelAetheolepis modelAetheolepis = new ModelAetheolepis();
    public static final ResourceLocation TEXTURE_ANOMALOCARIS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/anomalocaris.png");
    public static final ModelAnomalocaris modelAnomalocaris = new ModelAnomalocaris();
    public static final ResourceLocation TEXTURE_ARDUAFRONS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/arduafrons.png");
    public static final ModelArduafrons modelArduafrons = new ModelArduafrons();
    public static final ResourceLocation TEXTURE_ASPIDORHYNCHUS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/aspidorhynchus.png");
    public static final ModelAspidorhynchus modelAspidorhynchus = new ModelAspidorhynchus();
    public static final ResourceLocation TEXTURE_BALHUTICARIS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/balhuticaris.png");
    public static final ModelBalhuticaris modelBalhuticaris = new ModelBalhuticaris();
    public static final ResourceLocation TEXTURE_BUNDENBACHIELLUS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/bundenbachiellus.png");
    public static final ModelBundenbachiellus modelBundenbachiellus = new ModelBundenbachiellus();
    public static final ResourceLocation TEXTURE_COELOPHYSIS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/coelophysis.png");
    public static final ModelCoelophysis modelCoelophysis = new ModelCoelophysis();
    public static final ResourceLocation TEXTURE_DAPEDIUM = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/dapedium.png");
    public static final ModelDapedium modelDapedium = new ModelDapedium();
    public static final ResourceLocation TEXTURE_DIICTODON = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/diictodon.png");
    public static final ResourceLocation TEXTURE_EOSIMOPS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/eosimops.png");
    public static final ResourceLocation TEXTURE_PROSICTODON = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/prosictodon.png");
    public static final ResourceLocation TEXTURE_ROBERTIA = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/robertia.png");
    public static final ModelDiictodon modelDiictodon = new ModelDiictodon();
    public static final ResourceLocation TEXTURE_DIMETRODON = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/dimetrodon.png");
    public static final ModelDimetrodon modelDimetrodon = new ModelDimetrodon();
    public static final ResourceLocation TEXTURE_DUNYU = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/dunyu.png");
    public static final ModelDunyu modelDunyu = new ModelDunyu();
    public static final ResourceLocation TEXTURE_EASTMANOSTEUS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/eastmanosteus.png");
    public static final ModelEastmanosteus modelEastmanosteus = new ModelEastmanosteus();
    public static final ResourceLocation TEXTURE_EORAPTOR = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/eoraptor.png");
    public static final ModelEoraptor modelEoraptor = new ModelEoraptor();
    public static final ResourceLocation TEXTURE_ERYON = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/eryon.png");
    public static final ModelEryon modelEryon = new ModelEryon();
    public static final ResourceLocation TEXTURE_EUCHAMBERSIA = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/euchambersia.png");
    public static final ModelEuchambersia modelEuchambersia = new ModelEuchambersia();
    public static final ResourceLocation TEXTURE_EUGALEASPIS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/eugaleaspis.png");
    public static final ModelEugaleaspis modelEugaleaspis = new ModelEugaleaspis();
    public static final ResourceLocation TEXTURE_INOSTRANCEVIA = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/inostrancevia.png");
    public static final ModelInostrancevia modelInostrancevia = new ModelInostrancevia();
    public static final ResourceLocation TEXTURE_LASANIUS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/lasanius.png");
    public static final ModelLasanius modelLasanius = new ModelLasanius();
    public static final ResourceLocation TEXTURE_LESSEMSAURUS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/lessemsaurus.png");
    public static final ModelLessemsaurus modelLessemsaurus = new ModelLessemsaurus();
    public static final ResourceLocation TEXTURE_MACROMESODON = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/macromesodon.png");
    public static final ModelMacromesodon modelMacromesodon = new ModelMacromesodon();
    public static final ResourceLocation TEXTURE_MUSSAURUS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/mussaurus.png");
    public static final ModelMussaurus modelMussaurus = new ModelMussaurus();
    public static final ResourceLocation TEXTURE_NEEYAMBASPIS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/neeyambaspis.png");
    public static final ModelNeeyambaspis modelNeeyambaspis = new ModelNeeyambaspis();
    public static final ResourceLocation TEXTURE_NOTIDANOIDES = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/notidanoides.png");
    public static final ModelNotidanoides modelNotidanoides = new ModelNotidanoides();
    public static final ResourceLocation TEXTURE_OPHTHALMOSAURUS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/ophthalmosaurus.png");
    public static final ModelOphthalmosaurus modelOphthalmosaurus = new ModelOphthalmosaurus();
    public static final ResourceLocation TEXTURE_PLACERIAS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/placerias.png");
    public static final ModelPlacerias modelPlacerias = new ModelPlacerias();
    public static final ResourceLocation TEXTURE_POSTOSUCHUS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/postosuchus.png");
    public static final ModelPostosuchus modelPostosuchus = new ModelPostosuchus();
    public static final ResourceLocation TEXTURE_PITURIASPIS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/pituriaspis.png");
    public static final ModelPituriaspis modelPituriaspis = new ModelPituriaspis();
    public static final ResourceLocation TEXTURE_XINPUSAURUS = new ResourceLocation(LepidodendronMod.MODID + ":textures/entities/xinpusaurus.png");
    public static final ModelXinpusaurus modelXinpusaurus = new ModelXinpusaurus();

}