
package net.lepidodendron.item.crafting;

import net.lepidodendron.ElementsLepidodendronMod;
import net.lepidodendron.item.*;
import net.lepidodendron.item.entities.*;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;

@ElementsLepidodendronMod.ModElement.Tag
public class RecipeCookedMeats extends ElementsLepidodendronMod.ModElement {
	public RecipeCookedMeats(ElementsLepidodendronMod instance) {
		super(instance, 1092);
	}

	@Override
	public void init(FMLInitializationEvent event) {

		GameRegistry.addSmelting(new ItemStack(ItemAcanthodesRaw.block, (int) (1)), new ItemStack(ItemAcanthodesCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemBothriolepisRaw.block, (int) (1)), new ItemStack(ItemBothriolepisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemArandaspisRaw.block, (int) (1)), new ItemStack(ItemArandaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPteraspisRaw.block, (int) (1)), new ItemStack(ItemPteraspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEurypterusRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCyrtocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPromissumRaw.block, (int) (1)), new ItemStack(ItemPromissumCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSacabambaspisRaw.block, (int) (1)), new ItemStack(ItemSacabambaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemHibernaspisRaw.block, (int) (1)), new ItemStack(ItemHibernaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAmmoniteRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemHibbertopterusRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemFurcacaudaRaw.block, (int) (1)), new ItemStack(ItemFurcacaudaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemTerataspisRaw.block, (int) (1)), new ItemStack(ItemTerataspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemIsotelusRaw.block, (int) (1)), new ItemStack(ItemIsotelusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSquatinactisRaw.block, (int) (1)), new ItemStack(ItemSquatinactisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCheirurusRaw.block, (int) (1)), new ItemStack(ItemCheirurusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAsaphusRaw.block, (int) (1)), new ItemStack(ItemAsaphusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemWalliseropsRaw.block, (int) (1)), new ItemStack(ItemWalliseropsCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemQilinyuRaw.block, (int) (1)), new ItemStack(ItemQilinyuCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAphetocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEndocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCamerocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemOrthocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPoraspisRaw.block, (int) (1)), new ItemStack(ItemPoraspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPalaeodictyopteraDelitzschalaRaw.block, (int) (1)), new ItemStack(ItemPalaeodictyopteraCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemLimnoscelisRaw.block, (int) (1)), new ItemStack(ItemLimnoscelisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSchinderhannesRaw.block, (int) (1)), new ItemStack(ItemSchinderhannesCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemTitanichthysRaw.block, (int) (1)), new ItemStack(ItemTitanichthysCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemIchthyostegaRaw.block, (int) (1)), new ItemStack(ItemIchthyostegaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAmphibamusRaw.block, (int) (1)), new ItemStack(ItemAmphibamusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMixopterusRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemJaekelopterusRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPterygotusRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMegarachneRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemLunataspisRaw.block, (int) (1)), new ItemStack(ItemLunataspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSelenopeltisRaw.block, (int) (1)), new ItemStack(ItemSelenopeltisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemHemicyclaspisRaw.block, (int) (1)), new ItemStack(ItemHemicyclaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAteleaspisRaw.block, (int) (1)), new ItemStack(ItemAteleaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCephalaspisRaw.block, (int) (1)), new ItemStack(ItemCephalaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPsarolepisRaw.block, (int) (1)), new ItemStack(ItemPsarolepisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAegirocassisRaw.block, (int) (1)), new ItemStack(ItemAegirocassisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemThelodusRaw.block, (int) (1)), new ItemStack(ItemThelodusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemTullimonstrumRaw.block, (int) (1)), new ItemStack(ItemTullimonstrumCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCladoselacheRaw.block, (int) (1)), new ItemStack(ItemCladoselacheCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemHyneriaRaw.block, (int) (1)), new ItemStack(ItemHyneriaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAcutiramusRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAiniktozoonRaw.block, (int) (1)), new ItemStack(ItemAiniktozoonCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAkmonistionRaw.block, (int) (1)), new ItemStack(ItemAkmonistionCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemBelantseaRaw.block, (int) (1)), new ItemStack(ItemBelantseaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCampbellodusRaw.block, (int) (1)), new ItemStack(ItemCampbellodusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCoccosteusRaw.block, (int) (1)), new ItemStack(ItemCoccosteusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDracopristisRaw.block, (int) (1)), new ItemStack(ItemDracopristisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemKalbarriaRaw.block, (int) (1)), new ItemStack(ItemKalbarriaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPalaeoisopusRaw.block, (int) (1)), new ItemStack(ItemPalaeoisopusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPlatysomusRaw.block, (int) (1)), new ItemStack(ItemPlatysomusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemRhizodusRaw.block, (int) (1)), new ItemStack(ItemRhizodusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemXenacanthusRaw.block, (int) (1)), new ItemStack(ItemXenacanthusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemGemuendinaRaw.block, (int) (1)), new ItemStack(ItemGemuendinaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemParvancorinaRaw.block, (int) (1)), new ItemStack(ItemParvancorinaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCarcinosomaRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemKokomopterusRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPageaRaw.block, (int) (1)), new ItemStack(ItemEurypteridCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEglonaspisRaw.block, (int) (1)), new ItemStack(ItemEglonaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAcadoaradoxidesRaw.block, (int) (1)), new ItemStack(ItemAcadoaradoxidesCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAlacarisRaw.block, (int) (1)), new ItemStack(ItemAlacarisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSiberionRaw.block, (int) (1)), new ItemStack(ItemSiberionCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemBanffiaRaw.block, (int) (1)), new ItemStack(ItemBanffiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemYawunikRaw.block, (int) (1)), new ItemStack(ItemYawunikCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPomatrumRaw.block, (int) (1)), new ItemStack(ItemPomatrumCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemOpabiniaRaw.block, (int) (1)), new ItemStack(ItemOpabiniaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemLyrarapaxRaw.block, (int) (1)), new ItemStack(ItemLyrarapaxCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemTokummiaRaw.block, (int) (1)), new ItemStack(ItemTokummiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPaucipodiaRaw.block, (int) (1)), new ItemStack(ItemPaucipodiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAnomalocarisRaw.block, (int) (1)), new ItemStack(ItemAnomalocarisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMegalocephalusRaw.block, (int) (1)), new ItemStack(ItemMegalocephalusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemLaminacarisRaw.block, (int) (1)), new ItemStack(ItemLaminacarisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCambrorasterRaw.block, (int) (1)), new ItemStack(ItemCambrorasterCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCanadaspisRaw.block, (int) (1)), new ItemStack(ItemCanadaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEllipsocephalusRaw.block, (int) (1)), new ItemStack(ItemEllipsocephalusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemElrathiaRaw.block, (int) (1)), new ItemStack(ItemElrathiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEoredlichiaRaw.block, (int) (1)), new ItemStack(ItemEoredlichiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemJianshanopodiaRaw.block, (int) (1)), new ItemStack(ItemJianshanopodiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemKodymirusRaw.block, (int) (1)), new ItemStack(ItemKodymirusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemKerygmachelaRaw.block, (int) (1)), new ItemStack(ItemKerygmachelaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMarrellaRaw.block, (int) (1)), new ItemStack(ItemMarrellaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemNectocarisRaw.block, (int) (1)), new ItemStack(ItemNectocarisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemParadoxidesRaw.block, (int) (1)), new ItemStack(ItemParadoxidesCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemVestinautilusRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemYohoiaRaw.block, (int) (1)), new ItemStack(ItemYohoiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemParexusRaw.block, (int) (1)), new ItemStack(ItemParexusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSynophalosRaw.block, (int) (1)), new ItemStack(ItemSynophalosCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPikaiaRaw.block, (int) (1)), new ItemStack(ItemPikaiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSpathicephalusRaw.block, (int) (1)), new ItemStack(ItemSpathicephalusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemHylonomusRaw.block, (int) (1)), new ItemStack(ItemHylonomusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemYunnanozoonRaw.block, (int) (1)), new ItemStack(ItemYunnanozoonCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemHallucigeniaRaw.block, (int) (1)), new ItemStack(ItemHallucigeniaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMicrodictyonRaw.block, (int) (1)), new ItemStack(ItemMicrodictyonCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDeirocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemGoniocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDianiaRaw.block, (int) (1)), new ItemStack(ItemDianiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMetasprigginaRaw.block, (int) (1)), new ItemStack(ItemMetasprigginaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemTegopelteRaw.block, (int) (1)), new ItemStack(ItemTegopelteCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemWiwaxiaRaw.block, (int) (1)), new ItemStack(ItemWiwaxiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPoleumita.block, (int) (1)), new ItemStack(ItemPalaeoEscargots.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMaclurina.block, (int) (1)), new ItemStack(ItemPalaeoEscargots.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemOdontogriphusRaw.block, (int) (1)), new ItemStack(ItemPalaeoEscargots.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCyclonema.block, (int) (1)), new ItemStack(ItemPalaeoEscargots.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemXenusionRaw.block, (int) (1)), new ItemStack(ItemXenusionCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMimetasterRaw.block, (int) (1)), new ItemStack(ItemMimetasterCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemOmnidensRaw.block, (int) (1)), new ItemStack(ItemOmnidensCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemBasilocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemWebsteroprionRaw.block, (int) (1)), new ItemStack(ItemWebsteroprionCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCheloniellonRaw.block, (int) (1)), new ItemStack(ItemCheloniellonCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemOttoiaRaw.block, (int) (1)), new ItemStack(ItemOttoiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemHeterosteusRaw.block, (int) (1)), new ItemStack(ItemHeterosteusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMoschopsRaw.block, (int) (1)), new ItemStack(ItemMoschopsCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEryopsRaw.block, (int) (1)), new ItemStack(ItemEryopsCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCotylorhynchusRaw.block, (int) (1)), new ItemStack(ItemCotylorhynchusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemOphiacodonRaw.block, (int) (1)), new ItemStack(ItemOphiacodonCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCoelacanthusRaw.block, (int) (1)), new ItemStack(ItemCoelacanthusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemHelicoprionRaw.block, (int) (1)), new ItemStack(ItemHelicoprionCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPederpesRaw.block, (int) (1)), new ItemStack(ItemPederpesCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAcrolepisRaw.block, (int) (1)), new ItemStack(ItemAcrolepisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemGorgonopsRaw.block, (int) (1)), new ItemStack(ItemGorgonopsCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemInostranceviaRaw.block, (int) (1)), new ItemStack(ItemInostranceviaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAcanthostegaRaw.block, (int) (1)), new ItemStack(ItemAcanthostegaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSphenacodonRaw.block, (int) (1)), new ItemStack(ItemSphenacodonCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPlatyhystrixRaw.block, (int) (1)), new ItemStack(ItemPlatyhystrixCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDunkleosteusRaw.block, (int) (1)), new ItemStack(ItemDunkleosteusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemVivaxosaurusRaw.block, (int) (1)), new ItemStack(ItemVivaxosaurusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemScutosaurusRaw.block, (int) (1)), new ItemStack(ItemScutosaurusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEstemmenosuchusRaw.block, (int) (1)), new ItemStack(ItemEstemmenosuchusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemBushizheiaRaw.block, (int) (1)), new ItemStack(ItemBushizheiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPhantaspisRaw.block, (int) (1)), new ItemStack(ItemPhantaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSidneyiaRaw.block, (int) (1)), new ItemStack(ItemSidneyiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPharyngolepisRaw.block, (int) (1)), new ItemStack(ItemPharyngolepisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPlatycaraspisRaw.block, (int) (1)), new ItemStack(ItemPlatycaraspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemCrotalocephalusRaw.block, (int) (1)), new ItemStack(ItemCrotalocephalusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDalmanitesRaw.block, (int) (1)), new ItemStack(ItemDalmanitesCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDrepanaspisRaw.block, (int) (1)), new ItemStack(ItemDrepanaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEusthenopteronRaw.block, (int) (1)), new ItemStack(ItemEusthenopteronCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemLunaspisRaw.block, (int) (1)), new ItemStack(ItemLunaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemLungmenshanaspisRaw.block, (int) (1)), new ItemStack(ItemLungmenshanaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPanderichthysRaw.block, (int) (1)), new ItemStack(ItemPanderichthysCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPlatylomaspisRaw.block, (int) (1)), new ItemStack(ItemPlatylomaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemBugRaw.block, (int) (1)), new ItemStack(ItemBugCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemTraquairiusRaw.block, (int) (1)), new ItemStack(ItemTraquairiusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDiictodonRaw.block, (int) (1)), new ItemStack(ItemDiictodonCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemRobertiaRaw.block, (int) (1)), new ItemStack(ItemRobertiaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemProsictodonRaw.block, (int) (1)), new ItemStack(ItemProsictodonCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEosimopsRaw.block, (int) (1)), new ItemStack(ItemEosimopsCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMooreocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemRayonnocerasRaw.block, (int) (1)), new ItemStack(ItemPalaeoCalamari.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPrionosuchusRaw.block, (int) (1)), new ItemStack(ItemPrionosuchusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemListracanthusRaw.block, (int) (1)), new ItemStack(ItemListracanthusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemProterogyrinusRaw.block, (int) (1)), new ItemStack(ItemProterogyrinusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPhanerotinus.block, (int) (1)), new ItemStack(ItemPalaeoEscargots.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemRemigiomontanusRaw.block, (int) (1)), new ItemStack(ItemRemigiomontanusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemEdestusRaw.block, (int) (1)), new ItemStack(ItemEdestusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemPholiderpetonRaw.block, (int) (1)), new ItemStack(ItemPholiderpetonCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemClaudiosaurusRaw.block, (int) (1)), new ItemStack(ItemClaudiosaurusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMesosaurusRaw.block, (int) (1)), new ItemStack(ItemMesosaurusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAcanthostomatopsRaw.block, (int) (1)), new ItemStack(ItemAcanthostomatopsCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemIniopteryxRaw.block, (int) (1)), new ItemStack(ItemIniopteryxCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemMenaspisRaw.block, (int) (1)), new ItemStack(ItemMenaspisCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemGnathorhizaRaw.block, (int) (1)), new ItemStack(ItemGnathorhizaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemLabidosaurusRaw.block, (int) (1)), new ItemStack(ItemLabidosaurusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDviniaRaw.block, (int) (1)), new ItemStack(ItemDviniaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAnteosaurusRaw.block, (int) (1)), new ItemStack(ItemAnteosaurusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDiadectesRaw.block, (int) (1)), new ItemStack(ItemDiadectesCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemAlbertoniaRaw.block, (int) (1)), new ItemStack(ItemAlbertoniaCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemKaibabvenatorRaw.block, (int) (1)), new ItemStack(ItemKaibabvenatorCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemSaivodusRaw.block, (int) (1)), new ItemStack(ItemSaivodusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemTapinocephalusRaw.block, (int) (1)), new ItemStack(ItemTapinocephalusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemProcynosuchusRaw.block, (int) (1)), new ItemStack(ItemProcynosuchusCooked.block, (int) (1)), 0.35F);
		GameRegistry.addSmelting(new ItemStack(ItemDimetrodonRaw.block, (int) (1)), new ItemStack(ItemDimetrodonCooked.block, (int) (1)), 0.35F);


		GameRegistry.addSmelting(new ItemStack(ItemBushyAraucariaNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemColumnarisNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemBunyaNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemAethophyllumNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemAgathisNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemAraucarioxylonNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemTallAraucariaNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemRedwoodNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemSciadopitysNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemDawnRedwoodNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemAlpiaSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemBrachyphyllumSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemBristleconeSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemWollemiSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemTelemachusSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemPseudovoltziaSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemWachtlerinaSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemBuriadiaSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemQuadrocladusSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemOrtiseiaSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemUtrechtiaSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemWalchiaSeed.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemCordaitesSeeds.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);
		GameRegistry.addSmelting(new ItemStack(ItemMonkeyPuzzleAraucariaNuts.block, (int) (1)), new ItemStack(ItemRoastedPineNuts.block, (int) (1)), 0.15F);

	}
}
